# Generated by Django 5.0.8 on 2024-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
